import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactNode } from "react";
import { ToastContainer } from "react-toastify";

import { Box } from "@mui/material";
import { AuthProvider } from "@/contexts/AuthContext";
import { getColor } from "@/utils/getColor";
import AuthLayout from "@/components/layouts/AuthLayout";
import DateLocalizationProvider from "@/components/providers/DateLocalizationProvider";
import MainLayout from "@/components/layouts/MainLayout";
import Version from "@/components/services/Version";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const colors = {
  backgroundMain: getColor("backgroundMain"),
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
          <DateLocalizationProvider>
            <Version />
            <AuthProvider>
              <Box
                sx={{ height: "100vh", backgroundColor: colors.backgroundMain }}
              >
                 <AuthLayout>
                <MainLayout>{children}</MainLayout>
                </AuthLayout>
                <ToastContainer position="top-left" autoClose={1500} />
              </Box>
            </AuthProvider>
          </DateLocalizationProvider>
        
      </body>
    </html>
  );
}
